# Generated by Django 2.1.5 on 2019-01-26 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20190122_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='Autor')),
                ('text', models.CharField(max_length=500, verbose_name='Contenido')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(max_length=15, verbose_name='Etiqueta'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cms.Post'),
        ),
    ]
